### ISSUE TITLE
Iterable via for...of

### ISSUE THREAD

**Issue by DimitryDushkin** [AmpersandJS/ampersand-collection#68] opened 2015-09-13 10:02 UTC
Currently it's impossible to iterate over collection via `for...of` from ES2015 (some sort of Symbol iterable bug). Workaround is to iterate over `collection.models`.

**Comment by wraithgar** [comment] 2016-01-25 22:24
Duplicate of #35

**Closed by wraithgar** 2016-01-25 22:24 UTC
